### ISSUE TITLE
MyLife Error: Failed to send daily email

### ISSUE THREAD

**Issue by gsgqgyq** [einaregilsson/MyLife#13]
MyLife Error: Failed to send daily email
```
Traceback (most recent call last):
 File "/base/data/home/apps/p~****-mylife/20180125t214027.407186433536469488/models/dailymail.py", line 97, in send
   old_post, old_type = self.get_old_post(today)
 File "/base/data/home/apps/p~****-mylife/20180125t214027.407186433536469488/models/dailymail.py", line 190, in get_old_post
   old_list = Post.query().fetch(1, offset=random.randint(0, count-1))
 File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_dist/lib/python2.7/random.py", line 242, in randint
   return self.randrange(a, b+1)
 File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_dist/lib/python2.7/random.py", line 218, in randrange
   raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
```

Yesterday using the latest version 1.4 installation

**Comment by jonchui** [comment]
I've been getting this too! 

any ideas @einaregilsson ?

**Comment by einaregilsson** [comment]
Looks like the PostCounter class might have its count set to 0 for some reason, it's supposed to have a complete count of all posts. This happens when trying to get a random post. Can you see the PostCounter instance in the datastore, see what it looks like?

**Comment by gsgqgyq** [comment]
是这个吗？Is that it?
![](https://ws4.sinaimg.cn/large/006tKfTcly1fnvlvb2z0ej30lq09x0sq.jpg)

**Comment by einaregilsson** [comment]
Yes. There should be only on instance in the datastore. It counts the number of posts, but for some reason its count property is zero. Hmmmm.

**Comment by gsgqgyq** [comment]
So, how to fix it?
I'm sorry I don't understand technology ...

**Comment by einaregilsson** [comment]
@gagqgs Do you have any posts in the database? Have you written any posts? I'm not sure how this happens, but a quick fix, if you know roughly how many posts you have is just to manually edit the PostCounter object and set its count property to the number of posts you have. But that still doesn't fix the underlying bug.

**Comment by gsgqgyq** [comment]
I haven't written a diary yet.

**Comment by einaregilsson** [comment]
Ok, try writing one post in the web interface, then this should work. I'll try to fix the bug when I can, but I'm not sure when that will be.

**Comment by gsgqgyq** [comment]
Ok, thank you
Thank you for your work.
