### ISSUE TITLE
Importing ohlife entires in zip file causes error: "Failed to import: 'NoneType' object has no attribute 'strftime'" 

### ISSUE THREAD

**Issue by jonchui** [einaregilsson/MyLife#3]
Steps:
1. zip ohlife.txt entries as a zip file
2. import into mylife, via the "settings" page

**Comment by Scorpkinger** [comment]
Hi, I got the same issue there, but what weird is, the zip file can be uploaded locally, while it doesn't work on appspot.

**Comment by jonchui** [comment]
Ah must be a version difference in the unzipping? or python? 

@Scorpkinger go down the list of differences between the local and appspot tech stack and we can narrow down what the cause is

**Comment by einaregilsson** [comment]
Ok, @Scorpkinger ,  I've added a fix for this now. Please get the latest version of the sourcetest the import again and see if it works this time.

**Comment by einaregilsson** [comment]
Oh, also, if you just read the original blog post when installing this, please follow the instructions in http://einaregilsson.com/mylife-google-cloud-storage-support/ as well to set up a Google Cloud Storage bucket. That wasn't necessary in the first version, but now it is which makes the whole thing a bit more complicated, which is annoying :/

**Comment by Scorpkinger** [comment]
Thanks a lot, Einar, Everything just works fine now, LOL

**Comment by einaregilsson** [comment]
Ok, great to hear. Closing this issue then :)
