### ISSUE TITLE
Preserve inline image placements in text

### ISSUE THREAD

**Issue by jonchui** [einaregilsson/MyLife#4]
If my email says:

text a
[Inline imageA]
text b
[inline imageB]
text c

---

the final post says:

[Inline imageA]
[inline imageB]

text a
text b
text c

---

would be nice to preserve the inline image placements, since often we are referring to inline images

**Comment by jonchui** [comment]
I noticed this again as i was looking @ my past oh life entries, is it easy to do?

does the original email get stored, or does it get converted into plain text in the database? (ie. are all old posts unfixable? or is it just something we have to re-parse?)

**Comment by einaregilsson** [comment]
@jonchui I've just released version 1.3 https://github.com/einaregilsson/MyLife/releases which contains the random post feature as well as inline images. So, you can now send posts with inline images and they will be shown in the right place. Old posts are not updated however. Couple of reasons:

1. I can't do it automatically, as it could potentially overwrite manual changes that people have done to the post.
2. I didn't save the content_id of the attachments before, so in a post  with multiple images I wouldn't know where which image went.
3. It seems like a hassle, and I can't be bothered to do it 😆 

Anyway, let me know if you run into any problems.

**Comment by einaregilsson** [comment]
But if you feel like doing it yourself the original emails are stored in the RawMail collection...
