### ISSUE TITLE
Migrate images to Google Cloud Storage

### ISSUE THREAD

**Issue by einaregilsson** [einaregilsson/MyLife#5]
The apis used to add files to the Blobstore are being deprecated. Need to update to use Google Cloud Storage instead, and migrate existing images over.

**Comment by einaregilsson** [comment]
Fixed in https://github.com/einaregilsson/MyLife/commit/08075fc6acca1613610c10b6529a7da2c3dfa7e6

**Comment by einaregilsson** [comment]
New release added on releases page: https://github.com/einaregilsson/MyLife/releases

**Comment by jonchui** [comment]
Will this only be necessary if we want to include photos/images in the emails?

**Comment by einaregilsson** [comment]
Yes, if you don't have any photos and don't plan on having any than it doesn't really matter.
